import type { Job } from '@/types/job'
import type { FreelanceProject } from '@/types/freelance'
import type { SocialJobPost } from '@/types/socialJob'

/**
 * Bundled demo listings.
 *
 * Used ONLY when DEMO_MODE=true is set in the environment: API routes serve
 * these instead of querying Postgres, so the app can be previewed (and the
 * share feature exercised) with no database attached. Production deployments
 * simply leave DEMO_MODE unset and everything goes through Prisma as usual.
 */

const hoursAgo = (h: number) => new Date(Date.now() - h * 3_600_000).toISOString()
const daysAgo = (d: number) => new Date(Date.now() - d * 86_400_000).toISOString()
const inHours = (h: number) => new Date(Date.now() + h * 3_600_000).toISOString()
const inDays = (d: number) => new Date(Date.now() + d * 86_400_000).toISOString()

export const DEMO_JOBS: Job[] = [
    {
        id: 'demo-job-1',
        title: 'Senior Frontend Engineer',
        company: 'Nile Digital',
        location: 'Cairo, Egypt',
        datePosted: hoursAgo(3),
        remote: false,
        hybrid: true,
        salary: '45,000 - 60,000 EGP/mo',
        description: 'React, TypeScript and design-system work on a large-scale fintech dashboard.',
        url: 'https://example.com/jobs/senior-frontend-engineer-nile-digital',
        source: 'wuzzuf',
    },
    {
        id: 'demo-job-2',
        title: 'Remote Backend Developer (Node.js)',
        company: 'Sahara Cloud',
        location: 'Remote — MENA',
        datePosted: hoursAgo(7),
        remote: true,
        hybrid: false,
        salary: '$3,000 - $4,500/mo',
        description: 'Build distributed services in Node.js and PostgreSQL for a cloud cost platform.',
        url: 'https://example.com/jobs/remote-backend-developer-sahara-cloud',
        source: 'linkedin',
    },
    {
        id: 'demo-job-3',
        title: 'Data Analyst',
        company: 'Pyramid Analytics',
        location: 'Giza, Egypt',
        datePosted: daysAgo(1),
        remote: false,
        hybrid: false,
        salary: null,
        description: 'SQL, dashboards and stakeholder reporting for retail clients.',
        url: 'https://example.com/jobs/data-analyst-pyramid-analytics',
        source: 'indeed',
    },
    {
        id: 'demo-job-4',
        title: 'Product Designer (UI/UX)',
        company: 'Delta Labs',
        location: 'Remote — Worldwide',
        datePosted: daysAgo(2),
        remote: true,
        hybrid: false,
        salary: '$55k - $75k/yr',
        description: 'Own end-to-end product design for a B2B SaaS suite.',
        url: 'https://example.com/jobs/product-designer-delta-labs',
        source: 'glassdoor',
    },
    {
        id: 'demo-job-5',
        title: 'DevOps Engineer',
        company: 'Alexandria Systems',
        location: 'Alexandria, Egypt',
        datePosted: daysAgo(2),
        remote: false,
        hybrid: true,
        salary: '38,000 - 50,000 EGP/mo',
        description: 'Kubernetes, CI/CD pipelines and observability for e-commerce infrastructure.',
        url: 'https://example.com/jobs/devops-engineer-alexandria-systems',
        source: 'tanqeeb',
    },
    {
        id: 'demo-job-6',
        title: 'Marketing Specialist',
        company: 'Cairo Creatives',
        location: 'Cairo, Egypt',
        datePosted: daysAgo(3),
        remote: false,
        hybrid: false,
        salary: null,
        description: 'Performance marketing across social channels for regional brands.',
        url: 'https://example.com/jobs/marketing-specialist-cairo-creatives',
        source: 'wuzzuf',
    },
    {
        id: 'demo-job-7',
        title: 'Full-Stack Engineer (Remote)',
        company: 'Gulfware',
        location: 'Remote — Gulf',
        datePosted: daysAgo(4),
        remote: true,
        hybrid: false,
        salary: '$2,800 - $4,000/mo',
        description: 'Next.js + Node.js product team, shipping weekly.',
        url: 'https://example.com/jobs/full-stack-engineer-gulfware',
        source: 'linkedin',
    },
    {
        id: 'demo-job-8',
        title: 'QA Automation Engineer',
        company: 'Quantum Apps',
        location: 'Riyadh, Saudi Arabia',
        datePosted: daysAgo(5),
        remote: false,
        hybrid: false,
        salary: null,
        description: 'Playwright test suites for a logistics platform.',
        url: 'https://example.com/jobs/qa-automation-engineer-quantum-apps',
        source: 'indeed',
    },
]

export const DEMO_PROJECTS: FreelanceProject[] = [
    {
        id: 'demo-proj-1',
        title: 'Build a marketing landing page in Next.js',
        budget: '$450',
        deadline: inDays(6),
        skills: ['Next.js', 'Tailwind CSS', 'Figma'],
        description: 'One-page marketing site with subtle animations, deployed on Vercel.',
        url: 'https://example.com/freelance/landing-page-nextjs',
        source: 'freelancer',
    },
    {
        id: 'demo-proj-2',
        title: 'تصميم متجر إلكتروني متكامل',
        budget: '15,000 EGP',
        deadline: inDays(12),
        skills: ['WooCommerce', 'Design', 'Arabic'],
        description: 'متجر إلكتروني لبيع الملابس مع بوابات دفع مصرية وشحن تلقائي.',
        url: 'https://example.com/freelance/ecommerce-store-arabic',
        source: 'mostaql',
    },
    {
        id: 'demo-proj-3',
        title: 'Fix API rate-limiting bug in Node.js service',
        budget: '$180',
        deadline: inDays(3),
        skills: ['Node.js', 'Redis'],
        description: 'Debug and patch a token-bucket edge case causing 429s for legit traffic.',
        url: 'https://example.com/freelance/api-rate-limit-bug',
        source: 'freelancer',
    },
    {
        id: 'demo-proj-4',
        title: 'كتابة محتوى SEO لموقع تقني',
        budget: '6,000 EGP',
        deadline: null,
        skills: ['SEO', 'Writing', 'Arabic'],
        description: 'عشر مقالات محسنة لمحركات البحث حول الاستضافة والسحابة.',
        url: 'https://example.com/freelance/seo-content-arabic',
        source: 'nafezly',
    },
    {
        id: 'demo-proj-5',
        title: 'Mobile app UI polish (React Native)',
        budget: 'Not quoted yet',
        deadline: inDays(9),
        skills: ['React Native', 'Reanimated'],
        description: 'Smooth out transitions and gestures in a fitness tracking app.',
        url: 'https://example.com/freelance/react-native-ui-polish',
        source: 'freelancer',
    },
    {
        id: 'demo-proj-6',
        title: 'تطوير لوحة تحكم لإدارة الفواتير',
        budget: '22,000 EGP',
        deadline: inDays(20),
        skills: ['Dashboard', 'Vue', 'API'],
        description: 'لوحة تحكم لعرض الفواتير والتقارير الشهرية مع تصدير Excel.',
        url: 'https://example.com/freelance/invoices-dashboard',
        source: 'mostaql',
    },
]

export const DEMO_SOCIAL_POSTS: SocialJobPost[] = [
    {
        id: 'demo-social-1',
        title: 'Senior Frontend Engineer',
        authorName: 'Jane Doe',
        authorTitle: 'Engineering Manager at Nile Digital',
        authorImageUrl: null,
        description:
            'We are hiring a senior frontend engineer for our platform team! React + TypeScript, hybrid in Cairo. Referrals welcome — comment or DM.',
        salary: '$120k - $160k',
        location: 'Cairo, Egypt',
        remote: false,
        tags: ['Frontend', 'Full-Time'],
        recruiterContact: null,
        imageUrl: null,
        url: 'https://www.linkedin.com/posts/jane-doe_demo-activity-1',
        source: 'linkedin',
        createdAt: hoursAgo(5),
        expiresAt: inHours(43),
    },
    {
        id: 'demo-social-2',
        title: 'Remote AI/ML Engineer — apply this week',
        authorName: 'Ahmed Ali',
        authorTitle: 'Founder at Sahara Cloud',
        authorImageUrl: null,
        description:
            'Looking for a machine learning engineer to join our growing team. Fully remote, async-first culture, LLM fine-tuning focus.',
        salary: null,
        location: 'Remote',
        remote: true,
        tags: ['AI/ML', 'Remote'],
        recruiterContact: null,
        imageUrl: null,
        url: 'https://www.linkedin.com/posts/ahmed-ali_demo-activity-2',
        source: 'linkedin',
        createdAt: hoursAgo(20),
        expiresAt: inHours(28),
    },
    {
        id: 'demo-social-3',
        title: 'Fractional CTO needed',
        authorName: 'Sara Smith',
        authorTitle: 'CEO at EarlyCo',
        authorImageUrl: null,
        description:
            'Hiring a fractional CTO for 2 days a week. Contract engagement, Dubai-based or remote. Great equity package.',
        salary: null,
        location: 'Dubai, UAE',
        remote: false,
        tags: ['Fractional', 'Contract'],
        recruiterContact: null,
        imageUrl: null,
        url: 'https://www.linkedin.com/posts/sara-smith_demo-activity-3',
        source: 'linkedin',
        createdAt: daysAgo(1),
        expiresAt: inHours(5),
    },
]
