import type { Job } from '@/types/job'
import type { FreelanceProject } from '@/types/freelance'
import type { SocialJobPost } from '@/types/socialJob'
import type { LearningMaterial } from '@/types/material'
import type { FollowProfile } from '@/types/profile'

/**
 * Bundled demo listings.
 *
 * Used ONLY when DEMO_MODE=true is set in the environment: API routes serve
 * these instead of querying Postgres, so the app can be previewed (and the
 * share feature exercised) with no database attached. Production deployments
 * simply leave DEMO_MODE unset and everything goes through Prisma as usual.
 */

const hoursAgo = (h: number) => new Date(Date.now() - h * 3_600_000).toISOString()
const daysAgo = (d: number) => new Date(Date.now() - d * 86_400_000).toISOString()
const inHours = (h: number) => new Date(Date.now() + h * 3_600_000).toISOString()
const inDays = (d: number) => new Date(Date.now() + d * 86_400_000).toISOString()

export const DEMO_JOBS: Job[] = [
    {
        id: 'demo-job-1',
        title: 'Senior Frontend Engineer',
        company: 'Nile Digital',
        location: 'Cairo, Egypt',
        datePosted: hoursAgo(3),
        remote: false,
        hybrid: true,
        salary: '45,000 - 60,000 EGP/mo',
        description: 'React, TypeScript and design-system work on a large-scale fintech dashboard.',
        url: 'https://example.com/jobs/senior-frontend-engineer-nile-digital',
        source: 'wuzzuf',
        createdAt: hoursAgo(3),
    },
    {
        id: 'demo-job-2',
        title: 'Remote Backend Developer (Node.js)',
        company: 'Sahara Cloud',
        location: 'Remote — MENA',
        datePosted: hoursAgo(7),
        remote: true,
        hybrid: false,
        salary: '$3,000 - $4,500/mo',
        description: 'Build distributed services in Node.js and PostgreSQL for a cloud cost platform.',
        url: 'https://example.com/jobs/remote-backend-developer-sahara-cloud',
        source: 'linkedin',
        createdAt: hoursAgo(7),
    },
    {
        id: 'demo-job-3',
        title: 'Data Analyst',
        company: 'Pyramid Analytics',
        location: 'Giza, Egypt',
        datePosted: daysAgo(1),
        remote: false,
        hybrid: false,
        salary: null,
        description: 'SQL, dashboards and stakeholder reporting for retail clients.',
        url: 'https://example.com/jobs/data-analyst-pyramid-analytics',
        source: 'indeed',
        createdAt: daysAgo(2),
    },
    {
        id: 'demo-job-4',
        title: 'Product Designer (UI/UX)',
        company: 'Delta Labs',
        location: 'Remote — Worldwide',
        datePosted: daysAgo(2),
        remote: true,
        hybrid: false,
        salary: '$55k - $75k/yr',
        description: 'Own end-to-end product design for a B2B SaaS suite.',
        url: 'https://example.com/jobs/product-designer-delta-labs',
        source: 'glassdoor',
        createdAt: daysAgo(2),
    },
    {
        id: 'demo-job-5',
        title: 'DevOps Engineer',
        company: 'Alexandria Systems',
        location: 'Alexandria, Egypt',
        datePosted: daysAgo(2),
        remote: false,
        hybrid: true,
        salary: '38,000 - 50,000 EGP/mo',
        description: 'Kubernetes, CI/CD pipelines and observability for e-commerce infrastructure.',
        url: 'https://example.com/jobs/devops-engineer-alexandria-systems',
        source: 'tanqeeb',
        createdAt: daysAgo(2),
    },
    {
        id: 'demo-job-6',
        title: 'Marketing Specialist',
        company: 'Cairo Creatives',
        location: 'Cairo, Egypt',
        datePosted: daysAgo(3),
        remote: false,
        hybrid: false,
        salary: null,
        description: 'Performance marketing across social channels for regional brands.',
        url: 'https://example.com/jobs/marketing-specialist-cairo-creatives',
        source: 'wuzzuf',
        createdAt: daysAgo(3),
    },
    {
        id: 'demo-job-7',
        title: 'Full-Stack Engineer (Remote)',
        company: 'Gulfware',
        location: 'Remote — Gulf',
        datePosted: daysAgo(4),
        remote: true,
        hybrid: false,
        salary: '$2,800 - $4,000/mo',
        description: 'Next.js + Node.js product team, shipping weekly.',
        url: 'https://example.com/jobs/full-stack-engineer-gulfware',
        source: 'linkedin',
        createdAt: daysAgo(4),
    },
    {
        id: 'demo-job-8',
        title: 'QA Automation Engineer',
        company: 'Quantum Apps',
        location: 'Riyadh, Saudi Arabia',
        datePosted: daysAgo(5),
        remote: false,
        hybrid: false,
        salary: null,
        description: 'Playwright test suites for a logistics platform.',
        url: 'https://example.com/jobs/qa-automation-engineer-quantum-apps',
        source: 'indeed',
        createdAt: daysAgo(5),
    },
]

export const DEMO_PROJECTS: FreelanceProject[] = [
    {
        id: 'demo-proj-1',
        title: 'Build a marketing landing page in Next.js',
        budget: '$450',
        deadline: inDays(6),
        skills: ['Next.js', 'Tailwind CSS', 'Figma'],
        description: 'One-page marketing site with subtle animations, deployed on Vercel.',
        url: 'https://example.com/freelance/landing-page-nextjs',
        source: 'freelancer',
        createdAt: hoursAgo(4),
    },
    {
        id: 'demo-proj-2',
        title: 'تصميم متجر إلكتروني متكامل',
        budget: '15,000 EGP',
        deadline: inDays(12),
        skills: ['WooCommerce', 'Design', 'Arabic'],
        description: 'متجر إلكتروني لبيع الملابس مع بوابات دفع مصرية وشحن تلقائي.',
        url: 'https://example.com/freelance/ecommerce-store-arabic',
        source: 'mostaql',
        createdAt: hoursAgo(9),
    },
    {
        id: 'demo-proj-3',
        title: 'Fix API rate-limiting bug in Node.js service',
        budget: '$180',
        deadline: inDays(3),
        skills: ['Node.js', 'Redis'],
        description: 'Debug and patch a token-bucket edge case causing 429s for legit traffic.',
        url: 'https://example.com/freelance/api-rate-limit-bug',
        source: 'freelancer',
        createdAt: daysAgo(2),
    },
    {
        id: 'demo-proj-4',
        title: 'كتابة محتوى SEO لموقع تقني',
        budget: '6,000 EGP',
        deadline: null,
        skills: ['SEO', 'Writing', 'Arabic'],
        description: 'عشر مقالات محسنة لمحركات البحث حول الاستضافة والسحابة.',
        url: 'https://example.com/freelance/seo-content-arabic',
        source: 'nafezly',
        createdAt: daysAgo(3),
    },
    {
        id: 'demo-proj-5',
        title: 'Mobile app UI polish (React Native)',
        budget: 'Not quoted yet',
        deadline: inDays(9),
        skills: ['React Native', 'Reanimated'],
        description: 'Smooth out transitions and gestures in a fitness tracking app.',
        url: 'https://example.com/freelance/react-native-ui-polish',
        source: 'freelancer',
        createdAt: daysAgo(4),
    },
    {
        id: 'demo-proj-6',
        title: 'تطوير لوحة تحكم لإدارة الفواتير',
        budget: '22,000 EGP',
        deadline: inDays(20),
        skills: ['Dashboard', 'Vue', 'API'],
        description: 'لوحة تحكم لعرض الفواتير والتقارير الشهرية مع تصدير Excel.',
        url: 'https://example.com/freelance/invoices-dashboard',
        source: 'mostaql',
        createdAt: daysAgo(5),
    },
]

export const DEMO_SOCIAL_POSTS: SocialJobPost[] = [
    {
        id: 'demo-social-1',
        title: 'Senior Frontend Engineer',
        authorName: 'Jane Doe',
        authorTitle: 'Engineering Manager at Nile Digital',
        authorImageUrl: null,
        description:
            'We are hiring a senior frontend engineer for our platform team! React + TypeScript, hybrid in Cairo. Referrals welcome — comment or DM.',
        salary: '$120k - $160k',
        location: 'Cairo, Egypt',
        remote: false,
        tags: ['Frontend', 'Full-Time'],
        recruiterContact: null,
        imageUrl: null,
        url: 'https://www.linkedin.com/posts/jane-doe_demo-activity-1',
        source: 'linkedin',
        createdAt: hoursAgo(5),
        expiresAt: inHours(43),
    },
    {
        id: 'demo-social-2',
        title: 'Remote AI/ML Engineer — apply this week',
        authorName: 'Ahmed Ali',
        authorTitle: 'Founder at Sahara Cloud',
        authorImageUrl: null,
        description:
            'Looking for a machine learning engineer to join our growing team. Fully remote, async-first culture, LLM fine-tuning focus.',
        salary: null,
        location: 'Remote',
        remote: true,
        tags: ['AI/ML', 'Remote'],
        recruiterContact: null,
        imageUrl: null,
        url: 'https://www.linkedin.com/posts/ahmed-ali_demo-activity-2',
        source: 'linkedin',
        createdAt: hoursAgo(20),
        expiresAt: inHours(28),
    },
    {
        id: 'demo-social-3',
        title: 'Fractional CTO needed',
        authorName: 'Sara Smith',
        authorTitle: 'CEO at EarlyCo',
        authorImageUrl: null,
        description:
            'Hiring a fractional CTO for 2 days a week. Contract engagement, Dubai-based or remote. Great equity package.',
        salary: null,
        location: 'Dubai, UAE',
        remote: false,
        tags: ['Fractional', 'Contract'],
        recruiterContact: null,
        imageUrl: null,
        url: 'https://www.linkedin.com/posts/sara-smith_demo-activity-3',
        source: 'linkedin',
        createdAt: daysAgo(1),
        expiresAt: inHours(5),
    },
]

export const DEMO_MATERIALS: LearningMaterial[] = [
    { id: 'demo-mat-1', field: 'software-engineering', title: 'Backend Developer Roadmap', url: 'https://roadmap.sh/backend', type: 'docs', description: 'Step-by-step map of what to learn and in which order.', createdAt: daysAgo(3) },
    { id: 'demo-mat-2', field: 'software-engineering', title: 'CS50x: Introduction to Computer Science', url: 'https://cs50.harvard.edu/x/', type: 'course', description: 'Free Harvard course — the best starting point for fundamentals.', createdAt: daysAgo(5) },
    { id: 'demo-mat-3', field: 'software-engineering', title: 'The System Design Primer', url: 'https://github.com/donnemartin/system-design-primer', type: 'repo', description: 'Interview-focused system design notes with diagrams.', createdAt: daysAgo(8) },
    { id: 'demo-mat-4', field: 'software-engineering', title: 'Refactoring Guru — Design Patterns', url: 'https://refactoring.guru/design-patterns', type: 'article', description: null, createdAt: daysAgo(12) },
    { id: 'demo-mat-5', field: 'networking', title: 'Jeremy’s IT Lab — CCNA 200-301', url: 'https://www.youtube.com/@JeremysITLab', type: 'video', description: 'Free full CCNA course with labs.', createdAt: daysAgo(2) },
    { id: 'demo-mat-6', field: 'networking', title: 'Subnetting Mastery', url: 'https://www.subnetting.org/', type: 'article', description: 'Practice subnetting until it is automatic.', createdAt: daysAgo(6) },
    { id: 'demo-mat-7', field: 'cybersecurity', title: 'TryHackMe', url: 'https://tryhackme.com/', type: 'course', description: 'Guided hands-on labs for beginners.', createdAt: daysAgo(4) },
    { id: 'demo-mat-8', field: 'data-science-ai', title: 'Kaggle Learn', url: 'https://www.kaggle.com/learn', type: 'course', description: 'Short practical micro-courses in Python, SQL and ML.', createdAt: daysAgo(7) },
    { id: 'demo-mat-9', field: 'devops-cloud', title: 'Docker Docs — Get Started', url: 'https://docs.docker.com/get-started/', type: 'docs', description: null, createdAt: daysAgo(9) },
]

export const DEMO_PROFILES: FollowProfile[] = [
    { id: 'demo-prof-1', platform: 'linkedin', name: 'Mariam Adel', url: 'https://linkedin.com/in/mariam-adel-demo', headline: 'Senior Tech Recruiter · Fintech', postsAbout: 'Backend, mobile and QA roles in Cairo and remote', createdAt: daysAgo(1) },
    { id: 'demo-prof-2', platform: 'linkedin', name: 'Omar Khaled', url: 'https://linkedin.com/in/omar-khaled-demo', headline: 'Talent Acquisition Lead · Telecom', postsAbout: 'Network engineers, NOC and cloud support', createdAt: daysAgo(2) },
    { id: 'demo-prof-3', platform: 'facebook', name: 'Egypt Remote Jobs', url: 'https://facebook.com/groups/egypt-remote-jobs-demo', headline: 'Community group · 120k members', postsAbout: 'Daily remote openings for MENA candidates', createdAt: daysAgo(3) },
    { id: 'demo-prof-4', platform: 'linkedin', name: 'Nour Hassan', url: 'https://linkedin.com/in/nour-hassan-demo', headline: 'HR Business Partner · E-commerce', postsAbout: 'Internships and graduate programmes', createdAt: daysAgo(4) },
    { id: 'demo-prof-5', platform: 'telegram', name: 'Freelance Devs MENA', url: 'https://t.me/freelance_devs_mena_demo', headline: 'Channel · project leads & gigs', postsAbout: 'Short freelance web and app projects', createdAt: daysAgo(5) },
    { id: 'demo-prof-6', platform: 'x', name: 'Youssef Fathy', url: 'https://x.com/youssef_fathy_demo', headline: 'Engineering Manager · hiring often', postsAbout: 'Frontend and React roles, Europe remote', createdAt: daysAgo(6) },
    { id: 'demo-prof-7', platform: 'instagram', name: 'Design Jobs Cairo', url: 'https://instagram.com/design.jobs.cairo.demo', headline: 'Page · design & creative roles', postsAbout: 'UI/UX, motion and brand design openings', createdAt: daysAgo(7) },
    { id: 'demo-prof-8', platform: 'linkedin', name: 'Salma Ibrahim', url: 'https://linkedin.com/in/salma-ibrahim-demo', headline: 'Recruiter · Data & AI', postsAbout: 'Data analyst, data engineer and ML roles', createdAt: daysAgo(8) },
]
